-- Run after database/initial-schema.sql. Snapshot imported from metalectrics.com on 2026-07-24.
insert into public.categories (name, slug, description) values
  ('LiFePO4 Solar Batteries', 'lifepo4-solar-batteries', 'Lithium iron phosphate batteries for solar, UPS, and power backup.'),
  ('Motorcycle Batteries', 'motorcycle-batteries', 'Lightweight LiFePO4 starter batteries for motorcycles.'),
  ('Battery Accessories', 'battery-accessories', 'Battery cells, BMS units, and supporting components.')
on conflict (slug) do update set name = excluded.name, description = excluded.description;

insert into public.products (category_id, name, slug, sku, short_description, description, price_pkr, compare_at_price_pkr, stock_quantity, tags, specifications, cover_image_url, is_active, is_featured) values
((select id from public.categories where slug='lifepo4-solar-batteries'),'Alpha Ampere 51.2V 100Ah Lithium Battery','alpha-ampere-51-2v-100ah-lithium-battery','aa-51-100','Premium LiFePO4 battery with Bluetooth connectivity.','Model: Alpha51.2ML100. Premium LiFePO4 battery with smart Bluetooth connectivity and an exceptional lifespan.',229000,245000,0,array['lifepo4','solar','ups','featured'],jsonb_build_object('Chemistry','LiFePO4','Nominal Power','5120Wh','Nominal Voltage','51.2 V','Capacity','100Ah','Maximum Discharge Rate','1C','Charging Current','50A','Discharging Current','100A (DC)','Connectivity','Smart Bluetooth + RS485/WiFi Optional','Life','15 Years (8000 Life Cycles @ 0.5C & 25°C)'),'https://i.postimg.cc/BvRZZ47P/51v1.png',true,true),
((select id from public.categories where slug='lifepo4-solar-batteries'),'Alpha Ampere 24V 100Ah Lithium Battery','alpha-ampere-24v-100ah-lithium-battery','aa-24-100','Reliable LiFePO4 battery with smart Bluetooth.','Model: Alpha25.6ML100. A powerful and reliable LiFePO4 battery for various applications, featuring smart Bluetooth.',139000,149000,0,array['lifepo4','solar','ups','featured'],jsonb_build_object('Chemistry','LiFePO4 (Lithium Iron Phosphate)','Nominal Power','2560Wh','Nominal Voltage','25.6 V','Nominal Capacity','100Ah','Capacity','100Ah','Maximum Discharge Rate','1C','Charging Current','50A','Discharging Current','100A (DC)','Connectivity','Smart Bluetooth + Can/RS485 Optional','Life','15 Years (8000 Life Cycles @ 0.5C & 25°C)'),'https://i.postimg.cc/SxNxDZzR/24v1.png',true,true),
((select id from public.categories where slug='lifepo4-solar-batteries'),'Alpha Ampere 12V 100Ah Lithium Battery','alpha-ampere-12v-100ah-lithium-battery','aa-12-100','Versatile LiFePO4 drop-in replacement with Bluetooth.','Model: Alpha12.8ML100. A versatile LiFePO4 battery with smart Bluetooth, perfect for drop-in replacements.',78000,85000,0,array['lifepo4','solar','ups','featured'],jsonb_build_object('Nominal Voltage','12.8V','Nominal Capacity','100AH','Temperature Range','-10°C to 55°C','Charge Cut Off Voltage','14.6V','Discharge Cut Off Voltage','10V','Communication','Smart Bluetooth','Cell Technology','Lithium Iron Phosphate (LiFePO4)','Life','15 Years (8000 Life Cycles @ 0.5C)'),'https://i.postimg.cc/tRWJTnjq/12v1.png',true,true),
((select id from public.categories where slug='motorcycle-batteries'),'Alpha Ampere 12V 6.5Ah Lithium (LFP) Battery for Bike','alpha-ampere-12v-6-5ah-lithium-lfp-battery-bike','ab-12-100','LiFePO4 battery for self-start motorcycles.','Model: Alpha12SS6.',6200,7000,0,array['lifepo4','motorcycle','bike'],jsonb_build_object('Nominal Voltage','12.8V','Nominal Capacity','6500 mah','Temperature Range','-10°C to 55°C','Charge Cut Off Voltage','14.4V','Discharge Cut Off Voltage','10V','Compatibility','Any SelfStart Motorbike','Cell Technology','Lithium Iron Phosphate (LiFePO4)','Life','10 Years (2000 Life Cycles)'),'https://i.postimg.cc/MHmzYR61/bike12v1.png',true,false),
((select id from public.categories where slug='motorcycle-batteries'),'Alpha Ampere 12V 2.5Ah Lithium (LFP) Battery for Bike','alpha-ampere-12v-2-5ah-lithium-lfp-battery-bike','ab-13-100','LiFePO4 battery for kick-start motorcycles.','Model: Alpha12KS3.',4300,5000,0,array['lifepo4','motorcycle','bike'],jsonb_build_object('Nominal Voltage','12.8V','Nominal Capacity','2500 mah','Temperature Range','-10°C to 55°C','Charge Cut Off Voltage','14.4V','Discharge Cut Off Voltage','10V','Compatibility','Any Kick Start Motorbike','Cell Technology','Lithium Iron Phosphate (LiFePO4)','Life','10 Years (2000 Life Cycles)'),'https://i.postimg.cc/BQJSnhpp/bike13v1.png',true,false),
((select id from public.categories where slug='battery-accessories'),'REPT 3.2V 100Ah Cell Lithium Iron Phosphate (LFP)','rept-3-2v-100ah-cell-lithium-iron-phosphate-lfp','ac-12-100','LiFePO4 battery cell.','LiFePO4 battery cell.',9500,9800,0,array['lifepo4','cell','accessory'],jsonb_build_object('Nominal Voltage','3.2V','Nominal Capacity','100 ah','Chemistry','Lithium Iron Phosphate (LiFePO4)'),'https://i.postimg.cc/NjzBbQcC/REPTv1.png',true,false),
((select id from public.categories where slug='battery-accessories'),'Gotion 3.2V 27Ah Cell Lithium Iron Phosphate (LFP)','gotion-3-2v-27ah-cell-lithium-iron-phosphate-lfp','ac-13-100','LiFePO4 battery cell.','LiFePO4 battery cell.',3500,3800,0,array['lifepo4','cell','accessory'],jsonb_build_object('Nominal Voltage','3.2V','Nominal Capacity','27 ah','Chemistry','Lithium Iron Phosphate (LiFePO4)'),'https://i.postimg.cc/Z5RJrC1y/gotionv1.png',true,false),
((select id from public.categories where slug='battery-accessories'),'JK BMS 4S-8S 100A Li-ion/LiFePO4','jk-bms-4s-8s-100a-li-ion-lifepo4','ac-14-100','Battery management system with 1A balancing.','Balancing: 1 A, battery management system.',13500,14000,0,array['bms','lifepo4','accessory'],jsonb_build_object('Brand','JK','Active Balancer','1A','Discharge Current','100 A','Charge Current','50 A'),'https://onvolt.pl/wp-content/uploads/2025/09/a4b761cb-b394-4957-bd4e-a49e6b5b6c6d.jpg',true,false)
on conflict (slug) do update set
  name=excluded.name, sku=excluded.sku, short_description=excluded.short_description, description=excluded.description,
  price_pkr=excluded.price_pkr, compare_at_price_pkr=excluded.compare_at_price_pkr, tags=excluded.tags,
  specifications=excluded.specifications, cover_image_url=excluded.cover_image_url, is_active=excluded.is_active, is_featured=excluded.is_featured;

insert into public.product_images (product_id, image_url, alt_text, sort_order)
select p.id, i.image_url, p.name, i.sort_order
from (values
 ('aa-51-100','https://i.postimg.cc/BvRZZ47P/51v1.png',0),('aa-51-100','https://i.postimg.cc/DZsv8HRj/51v2.png',1),('aa-51-100','https://i.postimg.cc/kGmn8wmn/51v3.png',2),
 ('aa-24-100','https://i.postimg.cc/SxNxDZzR/24v1.png',0),('aa-24-100','https://i.postimg.cc/9Q8FSGGp/24v2.png',1),('aa-24-100','https://i.postimg.cc/Gp4h1HK1/24v3.png',2),
 ('aa-12-100','https://i.postimg.cc/tRWJTnjq/12v1.png',0),('aa-12-100','https://i.postimg.cc/4N13vCyj/12v2.png',1),('aa-12-100','https://i.postimg.cc/5NJ0F94w/12v3.png',2),
 ('ab-12-100','https://i.postimg.cc/MHmzYR61/bike12v1.png',0),('ab-12-100','https://i.postimg.cc/8kRkD8Rs/bike12v2.png',1),
 ('ab-13-100','https://i.postimg.cc/BQJSnhpp/bike13v1.png',0),('ab-13-100','https://i.postimg.cc/xTg0JKF2/bike13v2.png',1),
 ('ac-12-100','https://i.postimg.cc/NjzBbQcC/REPTv1.png',0),('ac-13-100','https://i.postimg.cc/Z5RJrC1y/gotionv1.png',0),
 ('ac-14-100','https://onvolt.pl/wp-content/uploads/2025/09/a4b761cb-b394-4957-bd4e-a49e6b5b6c6d.jpg',0)
) as i(sku,image_url,sort_order) join public.products p on p.sku=i.sku
where not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url=i.image_url);
